name: CI for Kitchen Calculator Only

on:
  push:
    paths:
      - 'project1-tests/Kitchen Calculator/Kitchen Calculator/**'
  pull_request:
    paths:
      - 'project1-tests/Kitchen Calculator/Kitchen Calculator/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build --output-on-failure